# Generated by Django 4.2.18 on 2025-01-21 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('img', models.ImageField(upload_to='news/')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=150, verbose_name='specialization')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='experience')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('clinic_name', models.CharField(max_length=150, verbose_name='clinic name')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='consultation fee')),
                ('is_consultation_free', models.BooleanField(default=False, verbose_name='is consultation free')),
                ('available_today', models.BooleanField(default=False, verbose_name='is available today')),
                ('rating_percentage', models.PositiveIntegerField(default=0, verbose_name='rating percentage')),
                ('patient_stories', models.PositiveIntegerField(default=0, verbose_name='patient stories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
